# Generated by Django 5.2.4 on 2025-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='weights',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
