# Generated by Django 5.2.4 on 2025-07-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_exercise_status_alter_exercise_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='status',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending')], default='active'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weights',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
