# Generated by Django 5.2.4 on 2025-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_exercise_repetitions_exercise_sets_exercise_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending')], default='active'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weights',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
