# Generated by Django 5.2.4 on 2025-07-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_remove_exercise_muscle_group_remove_exercise_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='exercise_name',
        ),
    ]
